### ISSUE TITLE
Error autoload.php not founded

### ISSUE THREAD

**Issue by frateralexander** [Firehed/php7ize#9]
I'm trying run php7ize but I have an error

$ php7ize 
Composer autoload.php could not be located

How to solve it ?

**Comment by Firehed** [comment]
This should be fixed in the latest version. If it's not working, please let me know and also include the output from the following commands:

* `which php7ize`
* `cwd`

That will help me diagnose the directory issues.

**Comment by frateralexander** [comment]
Dear Eric Stern,

Thanks for answer

I solved this problem ... but I don't know how to use php7ize

How could I use it ?

What options I could use to converter php files in a dir ?

Best Regards


2017-02-07 21:28 GMT-02:00 Eric Stern <notifications@github.com>:

**Comment by Firehed** [comment]
The usage options should be displayed if you run the command with no arguments. Right now it only supports running on one file at a time; you should be able run it over a directory with `xargs` or a small shell script (I chose not to build this in directly since it makes tracking or debugging the changes a lot harder when it's done to many files at a time)

**Comment by frateralexander** [comment]
Dear Eric Stern,

Thanks I'll tried to use it

Best Regards

2017-02-09 17:00 GMT-02:00 Eric Stern <notifications@github.com>:
